services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  api:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes: []
    environment:
      - REDIS_ADDR=redis:6379
      - FRONTEND_URL=http://localhost:5173 
      - DOMAIN=localhost
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    environment:
      - ENV=local # local | prod
      - DOMAIN=localhost
    volumes:
      # in prod only: nginx looks here for certs
      - /etc/letsencrypt:/etc/letsencrypt:ro
