services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
  api:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/app/videos
    environment:
      - REDIS_ADDR=redis:6379
      - FRONTEND_URL=http://localhost:5173
